SOURCES :=	src/builtins/builtin.c \
	src/builtins/builtin_cd.c \
	src/builtins/builtin_echo.c \
	src/builtins/builtin_env.c \
	src/builtins/builtin_exit.c \
	src/builtins/builtin_export.c \
	src/builtins/builtin_pwd.c \
	src/builtins/builtin_unset.c \
	src/command.c \
	src/command_expand.c \
	src/command_printing.c \
	src/command_utils.c \
	src/executor.c \
	src/executor_cmd.c \
	src/executor_heredoc.c \
	src/executor_io.c \
	src/exit_status.c \
	src/expander.c \
	src/expander_path.c \
	src/expander_utils.c \
	src/main.c \
	src/readline_loop.c \
	src/signals.c \
	src/token_str.c \
	src/token_utils.c \
	src/tokenizer.c \
	src/utils/alloc.c \
	src/utils/ft_atoi.c \
	src/utils/ft_itoa.c \
	src/utils/llist_mem.c \
	src/utils/llist_util.c \
	src/utils/memory.c \
	src/utils/protect.c \
	src/utils/str.c \
	src/utils/str_array.c \
	src/utils/str_comparing.c \
	src/utils/str_counting.c \
	src/utils/str_split.c \
